### ISSUE TITLE
Difference in parsing indented blocks between 2.3.1 and 2.4.0

### ISSUE THREAD

**Issue by renzbagaporo** [pyparsing/pyparsing#87]
Hi, 

The recent 2.4.0 update seems to have introduced different behavior when it comes to parsing indented blocks. The following snippets is a simplified form of our grammar (enough to replicate differences in behavior):

```python
import os
from pyparsing import *

indent_stack = [1]

key = Word(alphas) + Suppress(":")
stmt = Forward()

suite = indentedBlock(stmt, indent_stack)
body = key + suite

pattern = (Word(alphas) + Suppress("(") + Word(alphas) + Suppress(")"))
stmt << pattern

def key_parse_action(toks):
    print("Parsing '%s'..." % toks[0])

key.setParseAction(key_parse_action)
header = Suppress("[") + Literal("test") + Suppress("]")

content = (header + OneOrMore(indentedBlock(body, indent_stack, False)))
parser = OneOrMore(content)

parser.parseFile("./simple_file.txt", parseAll=True)
```

When parsing a sample `simple_file.txt` contents:

```
[test]
one: 
    two (three)
four:
    five (seven
```
`five (seven` here is incorrect. 2.3.1 fails immediately, while 2.4.0 seem to backtrack to parsing `four:` as evidenced by the print logs.

Another case is as follows:

```python
import os
from pyparsing import *

indent_stack = [1]

key = Word(alphas) + Suppress(":")
stmt = Forward()

suite = indentedBlock(stmt, indent_stack)
body = key + suite

pattern = (Word(alphas) + Suppress("(") + Word(alphas) + Suppress(")"))
stmt << pattern

def key_parse_action(toks):
    print("Parsing '%s'..." % toks[0])

key.setParseAction(key_parse_action)
header = Suppress("[") + Literal("test") + Suppress("]")
content = (header + OneOrMore(indentedBlock(body, indent_stack, False)))

contents = Forward()
suites = indentedBlock(content, indent_stack)

extra = Literal("extra") + Suppress(":") + suites
contents << (content | extra)

parser = OneOrMore(contents)

parser.parseFile("./simple_file.txt", parseAll=True)
```

With the test text as follows:

```
extra:
    [test]
    one: 
        two (three)
    four:
        five (seven)
extra:
    [test]
    one: 
        two (three)
    four:
        five (seven)
```

2.3.1 is able to parse this fine, while 2.4.0 fails. 

The full grammar is in https://github.com/espressif/esp-idf/blob/master/tools/ldgen/fragments.py if you need it.

**Comment by ptmcg** [comment]
There was a change in indentedBlock in this last release, in addressing #74, so this is the likely culprit. Thanks for submitting an easy-to-reproduce test case.

**Comment by renzbagaporo** [comment]
Hi @ptmcg, any updates on this issue?

**Comment by ptmcg** [comment]
Fixed in 2.4.1, released today

**Comment by renzbagaporo** [comment]
Thanks for the update @ptmcg. I noticed another issue though. With the same grammar,  2.4.1 onwards is unable to parse:

```
extra:
    [test]
    one: 
        two (three)
    four:
        five (seven)
extra:
    [test]
    one: 
        two (three)
    four:
        five (seven)

    [test]
    one: 
        two (three)
    four:
        five (seven)
```
while 2.3.1 is able to.

**Comment by renzbagaporo** [comment]
Also in #74, you mentioned:

> or add a conditional parameter to permit the user to choose which behavior they want

Did you manage to implement this? This might solve the backtracking behavior difference for me (exemplified by difference in handling `five (seven` above).

**Comment by ptmcg** [comment]
No I didn't. The changes I made addressed the sample that was included in that Issue, so a compatibility switch didn't seem necessary. I will try to look at this further tomorrow.

**Comment by ptmcg** [comment]
I can see that I'm going to have to promote this to a full-on class, and not just a helper method. For now I have a band-aid fix to address your particular case, but it still has limitations (assumes all `indentedBlock`s in a parser share the same `indentStack`, for instance). I also added this test case to the unit tests, and tweaked the grammar to give better error messages and locations (changed '+' to '-' in `content` and `extra`). Fix will be in 2.5.0a1.

**Comment by TMiguelT** [comment]
I'm just now realising that the original backup-stack functionality I implemented (#75) was complete garbage, because it makes a backup when you *call* the function, which is at the point of defining the grammar, not at the point of parsing an indented block. This may have been causing the troubles mentioned in this thread (not 100% sure, though).

Considering this, I'm wondering if something like the simple class below would solve this problem. Note that this class doesn't automatically add the indent/dedent/peer indent elements because for my use-case I need to be able to customize them all, but a general-use class would probably do this:

```python
class IndentCheckpoint(ParserElement):
    def __init__(self, indent_stack: List[int], expr: ParserElement):
        super().__init__()
        self.expr = expr
        self.stack = indent_stack

    def parseImpl(self, instring, loc, doActions=True):
        # Backup the stack whenever we react this element during the parse
        backup_stack = self.stack[:]
        try:
            return self.expr._parse(instring, loc, doActions, callPreParse=False)
        except (ParseException, IndexError):
            # On a parse failure, reset the stack
            self.stack[:] = backup_stack
            return loc, []
```

**Comment by ptmcg** [comment]
I'm still with you, just lagging a bit for work and general low-energy/malaise. Will look at for next pre-release (not many more...).

**Comment by ptmcg** [comment]
Here is a prototype for `IndentedBlock` as a class (implemented as an external class for now, referencing other pyparsing classes as imported under `pp`). Passes my simple tests, what do you think? (No separate indentStack variable - the indent stack is kept on the call stack itself inside parseImpl)

```
import pyparsing as pp


class IndentedBlock(pp.ParseElementEnhance):
    """
    Expression to match one or more expressions at a given indentation level.
    Useful for parsing text where structure is implied by indentation (like Python source code).
    """
    def __init__(self, expr, recursive=True):
        super().__init__(expr, savelist=True)
        self._recursive = recursive

    def parseImpl(self, instring, loc, doActions=True):
        # see if self.expr matches at the current location - if not it will raise an exception
        # and no further work is necessary
        self.expr.parseImpl(instring, loc, doActions)

        indent_col = pp.col(loc, instring)
        peer_parse_action = pp.matchOnlyAtCol(indent_col)
        peer_expr = pp.FollowedBy(self.expr).addParseAction(peer_parse_action)
        inner_expr = pp.Empty() + peer_expr.suppress() + self.expr

        if self._recursive:
            indent_parse_action = pp.conditionAsParseAction(lambda s, l, t, relative_to_col=indent_col:
                                                            pp.col(l, s) > relative_to_col)
            indent_expr = pp.FollowedBy(self.expr).addParseAction(indent_parse_action)
            inner_expr += pp.Optional(indent_expr + self)

        return pp.OneOrMore(pp.Group(inner_expr)).parseImpl(instring, loc, doActions)
```

Tested with:

```
  zzz aaa
  abc def
    ghi jkl
      mno pqr stu
      bbb dub
  xxx yyy
    ddd eee
```
and
```
foo
    bar
        car2
        dar3
    tar
        ear3
goo
```

**Comment by renzbagaporo** [comment]
Hi @ptmcg, @TMiguelT 

I had the chance to test 2.4.7 and unfortunately, it still fails parsing our grammar. This is an even closer reproduction of what we use:

```python
import os
from pyparsing import *

indentStack = [0]

def get_cond_block(contents):
    if_cond = Literal("if") + Literal("cond") + Suppress(":")
    elif_cond = Literal("elif") + Literal("cond") + Suppress(":")
    else_cond = Literal("else") + Suppress(":")

    return (if_cond + contents) + \
            ZeroOrMore(elif_cond + contents) + \
            Optional(else_cond + contents)

key = Literal("key")
key_value = Literal("val")

cond_block = Forward()
key_content = indentedBlock(OneOrMore(key_value | cond_block), indentStack)
key_body = key + Literal(":") + key_content

fragment_header = Literal("[") + Literal("type") + Suppress(":") + Literal("name") + Literal("]")
fragment_content = indentedBlock(OneOrMore(key_body), indentStack, False)
fragment_body = fragment_header + fragment_content

cond_content = key_content
cond_block << get_cond_block(cond_content)

top_cond_block = Forward()
top_cond_content = indentedBlock(OneOrMore(fragment_body | top_cond_block), indentStack)
top_cond_block << get_cond_block(top_cond_content)

file_content = indentedBlock(OneOrMore(fragment_body | top_cond_block), indentStack)

file_content.parseFile("sample_file.txt", parseAll=True)
```

Here is the test file:
```
if cond:
    [type:name]
    key:
        val
    key:
        val
        if cond:
            val
        elif cond:
            val
        else:
            val
elif cond:
    [type:name]
    key:
        val
else:
    [type:name]
    key:
        val

[type:name]
key:
    val
key:
    val
    if cond:
        val
    elif cond:
        val
    else:
        val
```

Here is how each version does with the file above:

- 2.3.1 succeeds
- 2.4.0 fails
- 2.4.7 succeeds

So far, so good. However, removing the first `else: val`:

```
if cond:
    [type:name]
    key:
        val
    key:
        val
        if cond:
            val
        elif cond:
            val
elif cond:
    [type:name]
    key:
        val
else:
    [type:name]
    key:
        val

[type:name]
key:
    val
key:
    val
    if cond:
        val
    elif cond:
        val
    else:
        val
```

In this case:

- 2.3.1 succeeds
- 2.4.7 fails

Maybe there are errors in our grammar itself? Any recommendations?
